# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inizio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(652, 592)
        self.btn_cliente = QtWidgets.QPushButton(Main)
        self.btn_cliente.setGeometry(QtCore.QRect(20, 80, 161, 241))
        self.btn_cliente.setObjectName("btn_cliente")
        self.label = QtWidgets.QLabel(Main)
        self.label.setGeometry(QtCore.QRect(20, 10, 621, 41))
        self.label.setObjectName("label")
        self.btn_magazzino = QtWidgets.QPushButton(Main)
        self.btn_magazzino.setGeometry(QtCore.QRect(230, 80, 171, 251))
        self.btn_magazzino.setObjectName("btn_magazzino")
        self.btn_acquisto = QtWidgets.QPushButton(Main)
        self.btn_acquisto.setGeometry(QtCore.QRect(442, 85, 181, 241))
        self.btn_acquisto.setObjectName("btn_acquisto")
        self.btn_backup = QtWidgets.QPushButton(Main)
        self.btn_backup.setGeometry(QtCore.QRect(110, 360, 151, 171))
        self.btn_backup.setObjectName("btn_backup")
        self.btn_statistche = QtWidgets.QPushButton(Main)
        self.btn_statistche.setGeometry(QtCore.QRect(360, 365, 161, 171))
        self.btn_statistche.setObjectName("btn_statistche")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
        self.btn_cliente.setText(_translate("Main", "Cliente"))
        self.label.setText(_translate("Main", "Scegli l\'operazione:"))
        self.btn_magazzino.setText(_translate("Main", "Magazzino"))
        self.btn_acquisto.setText(_translate("Main", "Acquisto"))
        self.btn_backup.setText(_translate("Main", "Backup"))
        self.btn_statistche.setText(_translate("Main", "Statistiche"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
