# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vista_operazioni_fumetti.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VistaFumetti(object):
    def setupUi(self, VistaOperazioniFumetti):
        VistaOperazioniFumetti.setObjectName("VistaOperazioniFumetti")
        VistaOperazioniFumetti.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.go_inserisci_fumetti = QtWidgets.QPushButton(VistaOperazioniFumetti)
        self.go_inserisci_fumetti.setGeometry(QtCore.QRect(40, 50, 103, 171))
        self.go_inserisci_fumetti.setObjectName("go_inserisci_fumetti")
        self.go_cerca_fumetti = QtWidgets.QPushButton(VistaOperazioniFumetti)
        self.go_cerca_fumetti.setGeometry(QtCore.QRect(250, 50, 103, 171))
        self.go_cerca_fumetti.setObjectName("go_cerca_fumetti")
        self.label = QtWidgets.QLabel(VistaOperazioniFumetti)
        self.label.setGeometry(QtCore.QRect(20, 10, 361, 18))
        self.label.setObjectName("label")

        self.retranslateUi(VistaOperazioniFumetti)
        QtCore.QMetaObject.connectSlotsByName(VistaOperazioniFumetti)

    def retranslateUi(self, VistaOperazioniFumetti):
        _translate = QtCore.QCoreApplication.translate
        VistaOperazioniFumetti.setWindowTitle(_translate("VistaFumetti", "Operazioni Fumetto"))
        self.go_inserisci_fumetti.setText(_translate("VistaFumetti", "Inserisci"))
        self.go_cerca_fumetti.setText(_translate("VistaFumetti", "Cerca"))
        self.label.setText(_translate("VistaFumetti", "Scegli l\'operazione:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VistaOperazioniFumetti = QtWidgets.QWidget()
    ui = Ui_VistaFumetti()
    ui.setupUi(VistaOperazioniFumetti)
    VistaOperazioniFumetti.show()
    sys.exit(app.exec_())
